name = "MaxEntropyModel"
uuid = "66ed6090-781a-458f-a06e-87f037f69e02"
authors = ["Humberto Carmona"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
